'''
main_chat_cli.py

Unified entry point for interactive chat workflows in the Explain2Me project.

This script orchestrates an end-to-end chat session with the Explain2Me
model, loading necessary configurations and initializing the pipeline
for real-time user interaction.

MODES
-----
- chat : Launch an interactive session where users can input queries and
         receive explanations from the Explain2Me assistant.

WORKFLOW
--------
Typical chat session workflow:

    1. Launch interactive chat
        → python main_chat_cli.py --mode chat

    2. Input queries in the terminal
        → You: <your question>

    3. Receive responses from the assistant
        → Assistant: <explanation>

    4. Exit chat at any time
        → Type 'exit' or 'quit'

This modular CLI design allows for potential future extensions with
additional modes while keeping the chat functionality independent
and easy to maintain.

RESULTS
-------
- Real-time assistant responses are printed in the terminal.
- No persistent files are generated by default.
- Hugging Face token is used for model access if available.

CONFIGURATION
-------------
- Paths and environment variables are managed via `.env`
- Inference and training settings are defined in `chat_configs.yaml`
  and `config.yaml`
- Config paths can be overridden via environment variables:
    - INF_CONFIG_PATH
    - TRAIN_CONFIG_PATH

PORTABILITY
-----------
- Uses pathlib for cross-platform path handling
- Compatible with local environments, Docker, cloud VMs, and Colab
- No hardcoded paths; everything is config-driven
- CLI interface allows launching chat from scripts or terminals

EXAMPLE
-------
Run the interactive chat session:

    python main_chat_cli.py --mode chat

Type your questions and receive explanations in real-time.
Type 'exit' or 'quit' to terminate the session.
'''


import argparse
import os
import sys
from pathlib import Path
import yaml
from dotenv import load_dotenv

from inference.chat_pipeline import Explain2MePipeline

# -------------------- PATH UTILS --------------------
def resolve_path(path_str, base_dir):
    if path_str is None:
        return None
    path = Path(path_str)
    return path if path.is_absolute() else base_dir / path


# -------------------- CHAT RUNNER --------------------
def run_chat(base_dir):
    # Load .env
    load_dotenv(resolve_path(".env", base_dir))

    # Load HF token
    hf_token = os.environ.get("HF_TOKEN")
    if not hf_token:
        print("Warning: Hugging Face token not found. Some models may fail.")

    # Config paths
    chat_config_path = resolve_path(os.getenv("CHAT_CONFIG_PATH"), base_dir) or base_dir / "inference" / "chat_configs.yaml"
    config_path = resolve_path(os.getenv("CONFIG_PATH"), base_dir) or base_dir / "config.yaml"

    # Load YAML configs
    with chat_config_path.open("r", encoding="utf-8") as f:
        chat_config = yaml.safe_load(f)
    with config_path.open("r", encoding="utf-8") as f:
        config = yaml.safe_load(f)

    # Initialize pipeline
    pipeline = Explain2MePipeline.from_config(chat_config, config, hf_token=hf_token)

    # Interactive chat
    print("Explain2Me Chat (type 'exit' or 'quit' to stop)\n")
    while True:
        try:
            user_input = input("You: ")
        except EOFError:
            break

        if user_input.lower() in ["exit", "quit"]:
            print("Exiting chat...")
            break

        try:
            response = pipeline.generate(user_input, streaming=False)
            print(f"Assistant: {response}\n")
        except Exception:
            print("Assistant: Something went wrong.\n")


# -------------------- CLI --------------------
def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--mode",
        type=str,
        choices=["chat"],
        required=True,
        help="Mode to run. Currently only 'chat' is supported."
    )
    args = parser.parse_args()

    base_dir = Path(__file__).resolve().parent
    sys.path.append(str(base_dir.parent))  # repo root for imports

    if args.mode == "chat":
        run_chat(base_dir)


if __name__ == "__main__":
    main()