model_id: meta-llama/Meta-Llama-3.1-8B-Instruct

training:
  output_dir: ./lora_model
  epochs: 6
  learning_rate: 2e-4
  per_device_batch_size: 1
  per_device_eval_batch_size: 1
  gradient_accumulation_steps: 4
  weight_decay: 0.01
  save_steps: 70
  eval_steps: 70

lora:
  r: 16
  alpha: 32
  dropout: 0.05

hub:
  repo_id: quent1sch/llama-3.1-8b-explain2me-lora
  strategy: every_save

wandb:
  project: explain2me-qlora