model_id: meta-llama/Meta-Llama-3.1-8B-Instruct

training:
  output_dir: ./lora_model
  epochs: 6
  learning_rate: 2e-4
  per_device_batch_size: 1
  per_device_eval_batch_size: 1
  gradient_accumulation_steps: 4
  weight_decay: 0.01
  save_steps: 70
  eval_steps: 70

lora:
  r: 16
  alpha: 32
  dropout: 0.05

hub:
  repo_id: quent1sch/llama-3.1-8b-explain2me-lora
  strategy: every_save

wandb:
  project: explain2me-qlora  
  # optional: put run id here if you want to force resume 
  #           from specific run, else just run_id: null
  # run_id can be obtained from a wandb run overview -> in Run path
  run_id: h57q6byd

dataset:
  hf_dataset_repo: quent1sch/explain2me
  test_split_ratio: 0.1
  seed: 42

evaluation_trainer:
  #wandb_project: explain2me-evaluation
  wandb_group: llama3-8b-qlora-v1
  wandb_name: trainer-test-evaluation
  adapter_id: quent1sch/llama-3.1-8b-explain2me-lora
  # hf_dataset_repo: quent1sch/explain2me
  # test_split_ratio: 0.1
  # seed: 42