_wandb:
    value:
        cli_version: 0.25.0
        e:
            azgs9mxdswzohhxwh180xdj1jc5ks2dc:
                codePath: training_pipeline/evaluate.py
                codePathLocal: training_pipeline/evaluate.py
                cpu_count: 2
                cpu_count_logical: 4
                disk:
                    /:
                        total: "1081101176832"
                        used: "123915055104"
                email: schmitzquentin1@gmail.com
                executable: /home/schmi/projects/explain2me/venv_explain2me/bin/python
                git:
                    commit: 3f8f46d6ab518d3df928745a5795a7781524f5b7
                    remote: https://github.com/quent1sch/explain2me.git
                host: QuentinSchmitz
                memory:
                    total: "12544360448"
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.39
                program: /home/schmi/projects/explain2me/training_pipeline/evaluate.py
                python: CPython 3.12.10
                root: /home/schmi/projects/explain2me
                startedAt: "2026-03-09T14:28:46.160219Z"
                writerId: azgs9mxdswzohhxwh180xdj1jc5ks2dc
        m: []
        python_version: 3.12.10
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 71
                - 98
            "2":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 71
                - 98
            "4": 3.12.10
            "5": 0.25.0
            "6": 5.2.0
            "12": 0.25.0
            "13": linux-x86_64
